### ISSUE TITLE
MRSA Potency Results Sept 2020

### ISSUE THREAD

**Issue by edwintse** [opensourceantibiotics/Series-2-Diarylimidazoles#25]
The following 9 compounds have been screened against MRSA by Paul Stapleton here at UCL. The MICs (ug/mL) are shown below.

![Untitled Wiley Document-1](https://user-images.githubusercontent.com/18062981/92769622-136dec80-f391-11ea-9a7a-d3c6c4e55493.jpeg)

Quick observations ([compare to existing known SAR](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/wiki/Potency-Evaluation-and-SAR))
- The original active control (**822**) had an MIC of 2
- Inactive control (**820**) as expected
- The resynthesis compound (**812**) looks to be inactive
- Addition of another phenyl ring (**831**) or flipping the orientation of the benzothiophene (**832**) appears to slightly lower the activity
- A phenyl in place of the 2-pyridyl (**834**), made as an SAR control for that part of the molecule, is not tolerated
- Benzothiazoles (**835** and **836**) are also not tolerated

**Comment by mattodd** [comment]
Well, the two compounds at MIC = 8 appear to suggest the need for an S up there in the northwest, but 835 and 836 would suggest the electronics matter. Are benzothiazoles harder to oxidise on the sulfur than benzothiophenes?

**Comment by MFernflower** [comment]
A sulfonamide would be interesting but 4-Sulfamoylbenzeneboronic acid is a bit pricey from sigma

**Comment by MFernflower** [comment]
@mattodd I think oxidizing benzothiazole ring systems causes them to open: https://www.nrcresearchpress.com/doi/abs/10.1139/cjc-2018-0459?journalCode=cjc#.X1ruWjV7mUk

**Comment by bendndi** [comment]
Hi all,
(Just catching up to the party on this one - saw some of these structures on twitter and some bells started ringing (both good and bad).

First up the negative: I'd very strongly recommend that you check this series for general cell / cytotoxicity  because there is a clear metal chelation motif in there (the bidentate between the pyridine and the imidazole) . In fact there is a PAINS motif which is close to these compounds which has exactly this 2-pyridyl - imidazole bidentate metal chelation motif. It's quite possible you're seeing activity due to metal sequestering, which would alos show up in general cell cytotox assays. The fact that removing the 2-pyridyl results in loss of activity (00834) reinforces this observation. I'd suggest making a 4-pyridiyl at this position as this would have similar global electronics in the core imidazole but would no longer have the metal chelator.

The negative / positive: We've worked on similar series (2-pyridyl-3-aminoimidazopyridines) for leish and chagas, saw similar SAR "subtleties" at the 3 position of the imidazole core, however we were also able to show that we could swap out the 2 pyridiyl for a non-chelating equivalent and retain potency so metal chelation worries and PAINS were eliminated as a concern.
 Even still, the only way we could get the compound metabolically stable (in >250 analogues) was by repacing the 2-pyridyl group: Taking this with the negative point above aout chelation I would strongly encourage running an broad analoging sweep around the 2 position of the imidazole, seeing if you could retain potency but replacing the 2-pyridiyl. (Replacing 2-pyridyl with N-H containing 5 membered heterocycles like 3-pyrazole or 4-imidazole was the way we got our mic clearance down). 
(manuscript fvor this project at DNDi expected to be put into rxv wihtin the next 2 months)

The positive: We have a large collection of relatively close analogues, some of which I may be able to source for you to screen. I'll look into it. Note that based on your early SAR it's unlikely any of our analogues would be active (we have an imidazopyridine core, which you've already shown to be inactive in OSA00814).

One last thing, I couldn't see anywhere your intiial hit MIC (00812) on your SAR tables, do you have that data?

**Comment by drc007** [comment]
@bendndi I guess it is also possible that the mechanism of action has a metal in the binding site?

**Comment by mattodd** [comment]
@bendndi This was in the original proposal - @danaklug can you please check if this is on the wiki somewhere? "In addition to the MRSA strain, all 15 compounds were evaluated for human cytotoxicity in two systems. The compounds all demonstrated a similar cytotoxicity in HEK293 cells with the concentration at 50% cytotoxicity (CC50) within twofold of 12 µg/mL for all compounds. The concentration at 10% haemolytic activity (HC10) in human red blood cells was > 32 µg/mL for all compounds. These results suggested a window of therapeutic activity between the antibiotic effects on MRSA and cytotoxic effects on human cells."

**Comment by MFernflower** [comment]
@danaklug @edwintse fluorochem is your best bet for purchasing the acetylpyrazine and 4-acetylpyridine 12 quid for 25 grams of each!!!!

**Comment by bendndi** [comment]
> @bendndi I guess it is also possible that the mechanism of action has a metal in the binding site?
> 
> If it was simple metal sequestration would you expect all compounds with this motif to have similar activity?

@drc007  One would think that if it were a general metal-chelation issue then there would be similar potecy in all compounds, but in our experience in anti-parasitic work this isn't the case - however we're using high content cellular screens where overall physicochemical properties can have major impact on potency at the phenotypic level (i.e. can compounds get where they need to go to have the cidal effect). A usual flag is large variations in Selectivity index across a series, where some compounds have IC50 / CC50 window and then a small change boosts the window or closes the window - always a cause for concern.

Agree 100% that it could be there is a metal in the binding site of the target - although this wouldn't aleviate the issue of general metal sequestering.

**Comment by bendndi** [comment]
> @bendndi This was in the original proposal - @danaklug can you please check if this is on the wiki somewhere? "In addition to the MRSA strain, all 15 compounds were evaluated for human cytotoxicity in two systems. The compounds all demonstrated a similar cytotoxicity in HEK293 cells with the concentration at 50% cytotoxicity (CC50) within twofold of 12 µg/mL for all compounds. The concentration at 10% haemolytic activity (HC10) in human red blood cells was > 32 µg/mL for all compounds. These results suggested a window of therapeutic activity between the antibiotic effects on MRSA and cytotoxic effects on human cells."

@mattodd  Does this mean that many of the compounds were more cytotoxic than they are anti-bacterial (CC50 12 mg/mL, most MICs > 12 mg/mL)?
Not sure what others would advise on this but in anti-parasitic cell based assays we would consider a Selectivity Index (SI, CC50 host cell / IC50) of < 5 as a major flag that what is being seen is general toxicity rather than a real anti-pathogen, and would want to see SI >10 fold to consider a series viable, and candidate SI higher than that.

**Comment by danaklug** [comment]
> @danaklug can you please check if this is on the wiki somewhere? "In addition to the MRSA strain, all 15 compounds were evaluated for human cytotoxicity in two systems. The compounds all demonstrated a similar cytotoxicity in HEK293 cells with the concentration at 50% cytotoxicity (CC50) within twofold of 12 µg/mL for all compounds. The concentration at 10% haemolytic activity (HC10) in human red blood cells was > 32 µg/mL for all compounds. These results suggested a window of therapeutic activity between the antibiotic effects on MRSA and cytotoxic effects on human cells."

Yes, the information is in the introductory text on the "Overview and Series Origins" page!

**Comment by MFernflower** [comment]
@danaklug @bendndi @mattodd It would be great if we could get a tox eval (perhaps vs human fibroblasts?) of 2 active and 2 inactive compounds to confirm or deny what COADD reported

**Comment by mattodd** [comment]
Just FYI 4 micrograms per mL for the active (MW 317.4) corresponds to 12.6 micromolar in new money.

**Comment by bendndi** [comment]
@danaklug  @mattodd  One queck question looking through these OSAntibiotics pages - do you have a tabvleanywhere with all the data i.e. a master spreadsheet? I saw one with loads of compounds and sourcing data, but could not see one with actual screening data. If you could point me in the right direction that would be really helpful.

**Comment by danaklug** [comment]
@bendndi Good catch, thanks. I've just added a tab to the [master spreadsheet](https://docs.google.com/spreadsheets/d/168-a1_l51Nfbms67eG8zU8p-EhEtEO26FUzRInbu7fY/edit#gid=1078638615) and have filled in the potency data that we have so far. Will also do clearance/ADME ASAP!
