### ISSUE TITLE
OSA Meeting Friday Oct 9th 2020

### ISSUE THREAD

**Issue by edwintse** [opensourceantibiotics/Series-2-Diarylimidazoles#32]
Meeting Oct 9th 2020 at 2pm UK time at https://ucl.zoom.us/j/92800004715. This page follows on from #30 .

Recording is [here](https://youtu.be/fQFZUeJ0AJE).
On the call:  @mattodd @edwintse @danaklug @drc007 @MFernflower 

1. **Mechanism of action**: Experiments ongoing (see #30). Check in in a couple of weeks.

2. **in vitro PK**: Monash data discussed in #29. 
a) Residual uncertainty about the units between original data and those from Monash. Comparable? Check inherited data to be sure. **Action**: Mat.
b) **Benzofuran compound (821)** will be evaluated for metabolic ID etc. More "drug-like" than the benzothiophene lead - Compound has been resynthesized by @edwintse which is great.

3. **MRSA and tox screening**.
MRSA: Next screen next week, awaiting approval by Paul Stapleton.
Tox: Can start next week in lab of Andreas Schatzlein, being arranged by @danaklug 

4. **Biofunctionalisation**: **Action** still on Mat to report about ongoing discussions with Hypha.

5. **Series Origin/Similarity Landscape**: Mat is awaiting clearance for the GSK conversation and will report back when that's received.

6. **Community updates**: Need 30-second video update using the Tha/Dana protocol (OpenSourceMalaria/TechOps#3) describing first MRSA results, to highlight new injections of compounds from @bendndi and collaborators, and to highlight new data from Monash. Action on @danaklug @edwintse to do a 30-second thing we can post <-- this isn't going away, guys...

7. **Inherited data** @TwistedSwisster kindly provided original CO_ADD report (#31). No testing vs. against other gram +ves?
Important new data on tox: not a huge selectivity window. However, the tox numbers are very flat across the molecules tested, meaning the tox may derive from a constant feature of the structure, e.g. the metal-binding potential of the 2-pyridyl system. **Experiment to do**: re-synthesize (if needed) and evaluate (for human cell tox) the phenyl (EGT 482), 3 and 4-pyridyl analogs to check if the 2 pyridine functional group is responsible.

8. **Compound Donations**. All of Ben's compounds have arrived and will be screened for potency.

9. **Synthetic Chemistry Update** by @edwintse and @danaklug 
Slides posted below. Incorporation of P-OCF3 suggestion by @MFernflower 

AOB:
11. Note: the informal codes we're using - are they aligned with the formal numbering system?
12. Ask Paul Stapleton to compare the MRSA potency methods he used with the COADD results and comment on any significant differences. **Action** on @danaklug Done. Awaiting response.
13. Are we likely to see any metabolic clearance in the MRSA potency assay? This seems unlikely, which would argue against a metabolite being responsible for the in vitro potency. (Paul has responded see bottom of GHI) 

**From meeting:**
14) suggestion of Negishi and cycloadditions as per #30. (Ben Perry)
15) @MFernflower suggested investigating activity vs Streptococcus pyogenes (can Paul Stapleton do this?). Are there other Gram+ves that are WHO high priorities? (YES - Enterococcus faecium) Perhaps lack of activity vs Gram -ve is due to accumulation problems? (will wait to see what MoA might say).

Actions other than the chemical targets discussed (can be checked as complete after the meeting).

- [ ]  ACTION ITEM: Mat to report back on collaboration possibilities with Hypha.
- [ ]  ACTION ITEM: Mat to report back from GSK on what can be shared publicly about the series history.
- [ ]  ACTION ITEM: Mat This meeting video to be posted on YouTube.
- [ ]  ACTION ITEM: Ed and Dana to make 30-second video highlighting the new project inputs.
- [ ]  ACTION ITEM: (didn't discuss in meeting) Mat to look into possible email update list using e.g. Mailchimp.

**Comment by mattodd** [comment]
Something for the agenda - use of e.g. Mailchimp for simple email-based newsletters, to complement other means of reaching out.

**Comment by edwintse** [comment]
<img width="1292" alt="Screen Shot 2020-10-09 at 2 25 30 pm" src="https://user-images.githubusercontent.com/18062981/95588425-51673a80-0a3b-11eb-922a-3a2ee74c8d19.png">

**Comment by danaklug** [comment]
Just got my pathogen list open - _E. faecium_ is high priority and _S. pneumoniae_ is medium priority, both Gram-positive. I'll have a look around for any screening options.

**Comment by bendndi** [comment]
Hi all, @mattodd 
Sorry I missed the call but it seems there was a question about the CLint data and units. 
Basically the uL/min/mg.pr is the unit used for "in vitro" clearance i.e. how rapidly the compound is cleared in the well. However using some simple scalling factor math you can extrapolate to predicted in vivo CLint, which is expressed in mL/min/kg.

This is really well explained on page 30 and 31 of the great cyprotex ADMe guide which you can find for free [here:](https://www.cyprotex.com/download-file/?download_file=ADME%20Guide.pdf) 

Some labs do this scaling before reporting, others don't and some (e.g. WuXi) will report both. To make it more complicated different labs and med chemists have a history of using different forms of the CLint as their "main" interpretatable data (e.g. I use the in vitro CLint since that's what I've always used, but others are more used to using the in vivo CLint, or the Extraction Ratio EH, or the T1/2 which are different units entirely. I guess the advantage of using the post-scaling in vivo Clint value is that it's arguably assay-condition independent (may be incorrect here of course)

**Comment by mattodd** [comment]
Thanks @bendndi . I'm attempting to download the guide you mentioned (https://www.cyprotex.com/guides) (thank you) but just to clarify on the simplest level, the two units are one order of magnitude out, so there is something else going on that I'm missing. I understand that there can be a difference for in vitro vs in vivo, but within one group there ought to be a standard.

**Comment by MFernflower** [comment]
@edwintse @danaklug N-methylated indole idea missing from diagram


Likely easily done via the Eschweiler–Clarke reaction

**Comment by danaklug** [comment]
We have had a reply from Paul with some additional information about the MRSA assay:

- Metabolism: "It is only speculation, but yes it is possible that the antibacterial activity could be derived from a metabolite." i.e., we should not rule out that metabolism is happening under assay conditions.

- UCL vs CO-ADD MIC results: "In MIC testing, a two-fold difference is not usually considered significant when comparing results between labs. Due to the growth media and the method used to interpret the MIC I would expect the CO-ADD protocol to show the compounds to be slightly more active in cases where growth is significantly reduced towards the end-point. The media I use supports more confluent growth of Staph. aureus and I use the gold standard of no visible growth in determining the MIC of compounds against this organism." i.e., the differences between results from the two assays are in line with what would be expected and our compounds _are_ showing consistent inhibition across assays. Good news!

**Comment by MFernflower** [comment]
What cell line is Andreas going to use for tox screening? @danaklug

**Comment by danaklug** [comment]
> What cell line is Andreas going to use for tox screening? @danaklug
@MFernflower I've just updated #3 with details.

**Comment by MFernflower** [comment]
@danaklug HEK cells will be fine for the task ahead - however I did kind of want to see human fibroblasts used since most MRSA infections start via a break in the skin.

**Comment by danaklug** [comment]
Link to this Issue has been created in "Project Meetings" wiki.
