### ISSUE TITLE
NO MEETING 30th July 2021

### ISSUE THREAD

**Issue by danaklug** [opensourceantibiotics/Series-2-Diarylimidazoles#85]
No pressing issues to discuss today; a summary of where things stand below: 

- **Potency**: Results from the latest set of compounds have come in (#84), but may need to be retested. Therefore we'll hold off on discussion until next week.
- **Chemistry**: Work on previous targets ongoing.
- **Toxicity**: Alex still working on completing her tox tables.
- **MoA**: I've been in touch with Lee by email and he is in the process of sourcing compounds at UNC to proceed with MIB experiments.
- **Chagas/Leish**: Benzimidazoles still to be shipped to NEU/DnDi - I'll try to get that going today and will post in a new issue when it's done.

@edwintse @drc007 @Giada-chem @loriferrins @QSimpson @mattodd @MFernflower @flavioemery

**Comment by MFernflower** [comment]
@edwintse @danaklug @mattodd This was an  alternative core idea I had sitting on my computer for  a while - just thought I should get it out there!

![image](https://user-images.githubusercontent.com/3164942/127797583-c7f30039-97fa-4d32-b7f9-9324be080419.png)

**Comment by lferrins** [comment]
@QSimpson and I have been chatting about the compounds that we are alkylating (see the bottom of [issue 79](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/79)). Turns out we are going to have to remake some of these compounds (all of the ones with the 4-fluorophenyl are done) and we are wondering if there would actually be better/more interesting compounds to make based on the activity results that we have to date. We would be keen to get your input in this and maybe we could discuss in our next meeting?
