### ISSUE TITLE
Daniel's compounds 

### ISSUE THREAD

**Issue by danielgedder** [opensourceantibiotics/Series-2-Diarylimidazoles#91]
Hello Everyone, I am forwarding the list of compounds that I have already published (.xls doc) and also the new ones in the figure as we talked about during the meeting. Please let me know which ones I should ship to you. Thank you in advance!
[DGS-BIOLOGICAL-ASSAYS-DATA.xls](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/files/7144413/DGS-BIOLOGICAL-ASSAYS-DATA.xls)
![meeting-10-09-21](https://user-images.githubusercontent.com/88835924/132868213-6fa926af-eef8-416f-a485-a119b561ea10.jpg)

**Comment by MFernflower** [comment]
@danielgedder I think this was talked about briefly but I think you said you were going to attempt to alkylate the para-fluro compound with n-propyl bromide?

**Comment by danielgedder** [comment]
@MFernflower yes, I am going to try this reaction asap. Should we wait to send the compounds when I've finished this one?

**Comment by mattodd** [comment]
Hi @danielgedder - thanks for posting the list of compounds you've made. A really nice set. I don't think we need to test any of them in the MRSA assay, purely because none have the 2-pyridyl (or some other potentially chelating moiety) motif that we know is needed for activity. @danaklug or @edwintse or @drc007 concur?

Yes, the next round of evaluation will take place next week Tuesday, so we have another week to play with. Minus the time it will take for the compounds to arrive then we might have a few more days during which you could try that alternative chemistry, but I'd say, if this is OK with you guys, that you could send us what you have so far, and then if the chemistry works out you could send a follow-up shipment?

**Comment by danielgedder** [comment]
Hi @mattodd, great! I have started to test other reactions to get the compounds and if I finish any new compound in time for this next biological assay I will let you know. But I think I will work to get a small set of compounds to ship all of them together. 

best regards,

**Comment by danielgedder** [comment]
Closing issue! Compounds were synthesized: [Daniel Gedder's ELN ](https://uk-mynotebook.labarchives.com/share/Daniel%2520Gedder/MC4wfDE1MjA3LzAvVHJlZU5vZGUvMzY1NjQ3MzYwNXwwLjA=)
